#ifndef LIBMV_REVISION_H_
#define LIBMV_REVISION_H_

#define LIBMV_VERSION_MAJOR 0
#define LIBMV_VERSION_MINOR 0
#define LIBMV_VERSION_PATCH 9
#define LIBMV_VERSION "0.0.9"

#endif //LIBMV_REVISION_H_
